### ISSUE TITLE
Custom Text Messages

### ISSUE THREAD

**Issue by TheGreenBandit** [tupoy-ya/TupoyeMenu#15]
### Problem

Funny idea that just make gameplay more enjoyable

### Solution

Be able to custom chat

### Reason

Funny

### Additional context

![3D94BDAF-C754-437A-893D-D9F97961BB6C](https://user-images.githubusercontent.com/106003542/196304937-aa5d6350-5d5b-4ad9-87a7-63a2defe2449.png)

**Comment by tupoy-ya** [comment]
Is this something you send to player or just show on your screen?

**Comment by TheGreenBandit** [comment]
Looks like it is sent to other players

**Comment by tupoy-ya** [comment]
I will probably add this when i make custom chat.
