### ISSUE TITLE
Request: Fov Changer

### ISSUE THREAD

**Issue by TheGreenBandit** [tupoy-ya/TupoyeMenu#30]
### Problem

None, just fun

### Solution

Fov changer

### Reason

Would just be a general improvent and something to mess around with

### Additional context

https://github.com/drdaxxy/gta5fov Its in this menu, could be taken from there

**Comment by tupoy-ya** [comment]
Relevant: https://github.com/gta-chaos-mod/ChaosModV/blob/master/ChaosMod/Effects/db/Screen/ScreenQuakeFOV.cpp.
