### ISSUE TITLE
[Request]: add anti npc

### ISSUE THREAD

**Issue by TheGreenBandit** [tupoy-ya/TupoyeMenu#31]
### Problem

Npc vehicles/peds can clog the roadways getting in ur way

### Solution

Add a anti npc option

### Reason

Would get peda out the way when ur doing things

### Additional context

https://github.com/sub1to/subVersion_2/tree/public/GTA%20internal Stuff can be found in this, theres a bunch of other features if you wanna check them out

**Comment by TheGreenBandit** [comment]
Btw, why so you have everything in tabs? Like when interacting with a player on the menu u have to go to a separate tab to tp to them and a separate one to do things to them

**Comment by tupoy-ya** [comment]
> Btw, why so you have everything in tabs? Like when interacting with a player on the menu u have to go to a separate tab to tp to them and a separate one to do things to them

Because usually i only want one type of actions on player.
This is also how YimMenu handled it's player tab before 94c5710abb53bd69480b543767001d0c666fae3f, and how YimMenu handles everything else right now just with vertical tabs.

**Comment by TheGreenBandit** [comment]
> Because usually i only want one type of actions on player.
> 
> This is also how YimMenu handled it's player tab before 94c5710abb53bd69480b543767001d0c666fae3f, and how YimMenu handles everything else right now just with vertical tabs.

Ah alright
