### ISSUE TITLE
[Bug]: Gui

### ISSUE THREAD

**Issue by TheGreenBandit** [tupoy-ya/TupoyeMenu#33]
### Describe the bug

When using gui your screen moves with your mouse

### Steps To Reproduce

load menu
open menu
try accessing tab

### Expected Behavior

screen should stay still while in menu

### Screenshots and/or Logs

not needed

### Store

Epic Games

### Build

- [X] This does not occur on unmodified YimMenu

**Comment by tupoy-ya** [comment]
Can't reproduce.
What do you mean by "screen moves with your mouse"?

**Comment by TheGreenBandit** [comment]
Ill record a video once im off school to show u

**Comment by TheGreenBandit** [comment]
Im able to get on tonight, ill send a video, then ill try clearing appdata

**Comment by TheGreenBandit** [comment]
https://user-images.githubusercontent.com/106003542/200095143-602bb6f5-75e6-4f26-bff2-3f5d689e9459.mp4

heres a vid

**Comment by tupoy-ya** [comment]
If you talking about camera rotating in menu it's because you have "Always Control" enabled.

**Comment by TheGreenBandit** [comment]
ah alright then
