### ISSUE TITLE
[Bug]: Chatbox causes crash

### ISSUE THREAD

**Issue by TheGreenBandit** [tupoy-ya/TupoyeMenu#35]
### Describe the bug

the gui bugs out causing crash idk

### Steps To Reproduce

use menu, go online use chat, wait a bit, crash

### Screenshots and/or Logs

```
<paste your logs here>
```

### Build

- [X] This does not occur on unmodified YimMenu

**Comment by tupoy-ya** [comment]
Can you send a crash log and commit you are using?
Maybe a screenshot of "the gui bugs out causing crash" if possible.
