### ISSUE TITLE
[Request]: Reopen Lua Pull

### ISSUE THREAD

**Issue by Clone69420** [tupoy-ya/TupoyeMenu#36]
### Problem

- None

### Solution

- None

### Reason

Ig it wouldnt be bad to update (https://github.com/tupoy-ya/TupoyeMenu/pull/6) to the latest commits and cmake stuff etc. also i wanna commit some nice stuff

### Additional context

- None

**Comment by tupoy-ya** [comment]
I can update [skid-scripting-lua](https://github.com/tupoy-ya/TupoyeMenu/tree/skid-scripting-lua) if you want but i'm too lazy to actually add lua myself.

[skid-scripting-lua](https://github.com/tupoy-ya/TupoyeMenu/tree/skid-scripting-lua) is based on:
https://github.com/maybegreat48/YimMenu
