### ISSUE TITLE
[Request]: Hotkeys for most of features

### ISSUE THREAD

**Issue by PrimeMK105** [tupoy-ya/TupoyeMenu#42]
### Problem

Example: After falling off from bike i want insta health regen, i could press button but instead i must press Insert>click button Self>click>click Heal>click>press Insert again.

### Solution

Example: Bind Heal on . button on numpad. Fall off>move hand to button on numpad>press it>character heals>press again>it stop regen. And no change of focus on menu. Also shows notification that hotkey button pressed.

### Reason

Make life easier with hotkeys.

**Comment by tupoy-ya** [comment]
I will add some features for now, but i will probably add some scripting language for binds later.
