### ISSUE TITLE
[Request]: Vehicle Ability Selector 

### ISSUE THREAD

**Issue by SlavicBlin** [tupoy-ya/TupoyeMenu#66]
### Solution

Would be cool if this was added just have some extra features in the fun vehicle features are.
i tried adding it myself but kept getting invalid command error since i am still new to the whole GTA menu stuff.

### Reason

Just feel like something like this would be kinda cool to have.

### Additional context

This is really low priorty and since the feature is buggy from what i heard i dont expect it to be added any time soon but as mentioned before just would be cool :

**Comment by tupoy-ya** [comment]
I myself want this option to be in the menu, however:
- I don't want to add something that is already being added to YimMenu.
- It would require me to make a fork of GTAV-Classes which would have to be maintained and this not something i want to do.

Sadly i'm pretty sure that this feature will not be added to YimMenu for a while, and you will have to wait or make it yourself.

About invalid command error, did you add the `vehicle_abilities.cpp` file and re-run cmake after this?

**Comment by tupoy-ya** [comment]
> Yes i did

Then sadly i don't know what to do about it as there is not enough information for me to diagnose the issue.

Or maybe i'm just lazy & stupid.
