### ISSUE TITLE
[Request]: New way to Save Vehicles

### ISSUE THREAD

**Issue by SlavicBlin** [tupoy-ya/TupoyeMenu#76]
### Problem

The old way to save vehicles ( Persist ) was kinda buggy and some people have requested for this feature to be brought back to this version of the menu.

### Solution

Have a better / similar way of saving vehicles just like saving outfits but better.
The persist vehicle thing allows to you to save them as json with attachments which is not needed.

### Reason

Sometimes you spawn a vehicle and do it up in the LCS part of the menu and would wish to spawn the car in another time with the same tunes you applied to it last time however this is currently not possible to my knowledge and requires you to either buy the car and do it up the same way and spawn it through personal vehicles or it requires you to redo up the car in LCS all over again.

### Additional context

I know someone requested this already and i have tried to add it to my version of the menu but with the new code that has been added since then it all messes which eachother and spits out alot of errors without working :D

**Comment by tupoy-ya** [comment]
I don't think i will be able to add any features to the menu for now, some of the recent lua changes make it impossible for me to link the menu locally.

**Comment by SlavicBlin** [comment]
> I don't think i will be able to add any features to the menu for now, some of the recent lua changes make it impossible for me to link the menu locally.

Ahh I see well thanks for letting me know then 👍

**Comment by SlavicBlin** [comment]
Brother is putting in the work recently mad respect ❤️

**Comment by SlavicBlin** [comment]
@tupoy-ya do you have another form of donation rather than crypto? Something like buymeacoffee if not is your XMR address still valid?

**Comment by tupoy-ya** [comment]
> Do you have another form of donation rather than crypto? Something like buymeacoffee?

No as I don't have anywhere to withdraw to.

> Is your XMR address still valid?

Yes it is.

**Comment by SlavicBlin** [comment]
> > Do you have another form of donation rather than crypto? Something like buymeacoffee?
> 
> No as I don't have anywhere to withdraw to.
> 
> > Is your XMR address still valid?
> 
> Yes it is.

Damn xmr appears really hard to obtain in uk for some reason do you have any other wallets like ltc?

**Comment by tupoy-ya** [comment]
> Damn xmr appears really hard to obtain in uk for some reason do you have any other wallets like ltc?

Made myself a Litecoin wallet.
`ltc1qpwfprvt5pdu766v7dat9yhv9jzgajakxgs0r4c`

**Comment by SlavicBlin** [comment]
> > Damn xmr appears really hard to obtain in uk for some reason do you have any other wallets like ltc?
> 
> Made myself a Litecoin wallet. `ltc1qpwfprvt5pdu766v7dat9yhv9jzgajakxgs0r4c`

Alright I’ll send you some ltc as a thank you

**Comment by SlavicBlin** [comment]
> > Damn xmr appears really hard to obtain in uk for some reason do you have any other wallets like ltc?
> 
> Made myself a Litecoin wallet. `ltc1qpwfprvt5pdu766v7dat9yhv9jzgajakxgs0r4c`

There you go brother should have received it by now, it’s nothing crazy but hope it buys you a drink or something 😂
