### ISSUE TITLE
[Bug]: mt game keeps chrshing when i use xenos to inject the menu

### ISSUE THREAD

**Issue by cash121212** [tupoy-ya/TupoyeMenu#81]
### Describe the bug

game crashing when i use xenos to inject it

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

None

### Build

- [X] I've confirmed the issue exists on the latest version of TupoyeMenu and does not exist on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by tupoy-ya** [comment]
No logs, pretty sure the menu was out of date when the issue was made.
