### ISSUE TITLE
[Bug]: Weapon wheel isn't working

### ISSUE THREAD

**Issue by Raiskale** [tupoy-ya/TupoyeMenu#86]
### Describe the bug

Doesn't let use weapon wheel to select guns.

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

None

### Language

English

### Build

- [X] I've confirmed the issue exists on the latest version of TupoyeMenu and does not exist on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by SlavicBlin** [comment]
you sure you didnt disable it by accident?
ill test in 5 mins

**Comment by Raiskale** [comment]
> you sure you didnt disable it by accident? ill test in 5 mins

Weapon wheel does work with other mods i use. This one nope..

**Comment by SlavicBlin** [comment]
> > you sure you didnt disable it by accident? ill test in 5 mins
> 
> Weapon wheel does work with other mods i use. This one nope..

There is a option somewhere in the menu if i remeber to remove hud componenets maybe you turned it off by accident

**Comment by SlavicBlin** [comment]
mine appears to be working fine 
![image](https://github.com/TupoyeMenu/TupoyeMenu/assets/95110595/59148265-6a4b-4ebf-b71c-8e5eb507b81d)

**Comment by Raiskale** [comment]
> mine appears to be working fine ![image](https://private-user-images.githubusercontent.com/95110595/291248273-59148265-6a4b-4ebf-b71c-8e5eb507b81d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTU2MDAsIm5iZiI6MTcwMjg5NTMwMCwicGF0aCI6Ii85NTExMDU5NS8yOTEyNDgyNzMtNTkxNDgyNjUtNmE0Yi00ZWJmLWI3MWMtOGU1ZWI1MDdiODFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEwMjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NzM0NjU0ZWRiMzE5NzU2ODBhMWVlY2VmYmJiNTEyMjc5ODU0ZmUwMTAyMjY2NDM0NWM0NjBhMjFlYzE5ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C0cPDa7RGfX3y4JRypGnvfCtXba2AcK2Sk87zZzDmN4)

I'll go see if i've disabled something by accident.

**Comment by SlavicBlin** [comment]
> I'll go see if i've disabled something by accident.

yeah go to self ---> Self ---> scroll down -----> Hud ----> show all
![image](https://github.com/TupoyeMenu/TupoyeMenu/assets/95110595/16774824-b0b2-402e-b275-830baecd32b7)

**Comment by Raiskale** [comment]
> > I'll go see if i've disabled something by accident.
> 
> yeah go to self ---> Self ---> scroll down -----> Hud ----> show all ![image](https://private-user-images.githubusercontent.com/95110595/291249140-16774824-b0b2-402e-b275-830baecd32b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTU2OTMsIm5iZiI6MTcwMjg5NTM5MywicGF0aCI6Ii85NTExMDU5NS8yOTEyNDkxNDAtMTY3NzQ4MjQtYjBiMi00MDJlLWIyNzUtODMwYmFlY2QzMmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDEwMjk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MTc0YTQ1Njk5Zjg2MzBhZWMxZmM2NjdhMTFmMmFjMzQyNTNiNDk0ODRiMGE0YmEwOWZkNTM4YTRjM2VhYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OM7garuoEZHzb6enAqMs6EMzMs4QkyU3MIzwLMAulvI)

works now, my bad :)

**Comment by Raiskale** [comment]
solved
