### ISSUE TITLE
[Request]: Update faster from YimMenu

### ISSUE THREAD

**Issue by Ahmad23145** [tupoy-ya/TupoyeMenu#89]
### Problem

Update faster

### Solution

Update faster

### Reason

I dont wanna wait

**Comment by Ahmad23145** [comment]
@tupoy-ya update

**Comment by tupoy-ya** [comment]
> @tupoy-ya update

![image](https://c.tenor.com/o_-6ngnOy5YAAAAC/rent-give-me-rent.gif)

**Comment by ClapperJuan** [comment]
real

**Comment by Ahmad23145** [comment]
> > @tupoy-ya update
> 
> ![image](https://camo.githubusercontent.com/953ef2a9c7078dc007c59f363a79305cdeae64580d9b4172e390de1d27187d8a/68747470733a2f2f632e74656e6f722e636f6d2f6f5f2d366e676e4f79355941414141432f72656e742d676976652d6d652d72656e742e676966) [ ](https://camo.githubusercontent.com/953ef2a9c7078dc007c59f363a79305cdeae64580d9b4172e390de1d27187d8a/68747470733a2f2f632e74656e6f722e636f6d2f6f5f2d366e676e4f79355941414141432f72656e742d676976652d6d652d72656e742e67

@tupoy-ya When will you update?

**Comment by tupoy-ya** [comment]
> @tupoy-ya When will you update?

When I feel like it.

**Comment by SlavicBlin** [comment]
> > @tupoy-ya When will you update?
> 
> When I feel like it.

standing on bidness
