### ISSUE TITLE
[Request]: Add More Crash Options

### ISSUE THREAD

**Issue by Ahmad23145** [tupoy-ya/TupoyeMenu#90]
### Problem

I want to crash people with more than 2 Crashes

### Solution

.

### Reason

I want to have more crashes

### Additional context

[Crashes.zip](https://github.com/TupoyeMenu/TupoyeMenu/files/15404026/Crashes.zip)

**Comment by Ahmad23145** [comment]
@tupoy-ya Please respond :(((

**Comment by ClapperJuan** [comment]
Slight chance he will respond but if he does there is no way he will add this himself as this menu is simply a " Lite " version on YimMenu with all the bloat features removed, you could look into adding crash options yourself but there is a high chance that most public code will be blocked by most if not all menus, YimMenu and TupoyeMeny in general are not built to be a Toxic menu but iam sure there is luas out there that you could try which have more crashing options. hope my response helps have a good day!

**Comment by Ahmad23145** [comment]
If I add them myself it gives me a error that its not allowed and TupoyeMenu doesn't support lua scripts

**Comment by ClapperJuan** [comment]
Yeah thats the things with Tupoye it has lua support but if you want to use them you need to recode them in order to call the tabs that are used in Tupoye, i tried messing around with it a while back and got it to display an extra tab when injecting a simple lua but i couldnt really figure out the rest, also are you getting this error when building the menu or when you are injected?

**Comment by Ahmad23145** [comment]
I get this error when building

**Comment by ClapperJuan** [comment]
could you prove the error if you possible?
most of the time it will tell you if your missing potential lines of codes that it wants to call but is unable to since it dont exist.

**Comment by Ahmad23145** [comment]
![image_2024-05-22_163639477](https://github.com/TupoyeMenu/TupoyeMenu/assets/165480150/8654b770-d1df-40b3-993c-f39da278d8ef)
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	E0322	object of abstract class type "big::crash_player" is not allowed:	TupoyeMenu.dll - x64-Release	C:\Users\Administrator\source\repos\TupoyeMenu\src\backend\commands\player\crash\crash_player.cpp	49

**Comment by Ahmad23145** [comment]
@ClapperJuan Do you know how to fix?

**Comment by ClapperJuan** [comment]
It’s not finding / wanting to call the g_crash_player I don’t remember fully but I think if you Ctrl plus left click it should take you to where the error.

**Comment by ClapperJuan** [comment]
When I get back I will look at some of my code to try and recreate a similar error and help you from there

**Comment by Ahmad23145** [comment]
Ok thanks a lot for helping me

**Comment by Ahmad23145** [comment]
@ClapperJuan you are free to download the crashes if you want to 
[Crashes.zip](https://github.com/TupoyeMenu/TupoyeMenu/files/15408158/Crashes.zip)

**Comment by ClapperJuan** [comment]
> @ClapperJuan you are free to download the crashes if you want to [Crashes.zip](https://github.com/TupoyeMenu/TupoyeMenu/files/15408158/Crashes.zip)

this will be useful thank you

**Comment by ClapperJuan** [comment]
iam building a quick tester version then i will try and build the version with your crashes and work from there

**Comment by ClapperJuan** [comment]
alright it let me build it fine, iam gonna test it in game and let you know

**Comment by ClapperJuan** [comment]
in game it does not work amma just work on it and come back with an answer when i got one

**Comment by ClapperJuan** [comment]
alright i got a build working i will test in game now, also is it only " crash_player.cpp " that is giving you problems? or do the other give similar errors?

**Comment by ClapperJuan** [comment]
have to rebuild it and test it again since the debug version of the dll is just crashing my game

**Comment by ClapperJuan** [comment]
seems to be working fine i will attempt to kick a player from the lobby to be sure

**Comment by ClapperJuan** [comment]
[crash_player.zip](https://github.com/TupoyeMenu/TupoyeMenu/files/15408792/crash_player.zip)
This seems to be working fine.

**Comment by ClapperJuan** [comment]
Forgot to mention you may need to change the Button name in kicks&crashed.cpp I think is that it was called but I tested it seems to being doing what it states has a hard time crashing though had to spam it a few times

**Comment by Ahmad23145** [comment]
> alright i got a build working i will test in game now, also is it only " crash_player.cpp " that is giving you problems? or do the other give similar errors?

No all crashes except tse and invalid model crash that is being given

**Comment by Ahmad23145** [comment]
> [crash_player.zip](https://github.com/TupoyeMenu/TupoyeMenu/files/15408792/crash_player.zip) This seems to be working fine.

What building version did you use

**Comment by tupoy-ya** [comment]
I'm too lazy to add more crashes, even the two TupoyeMenu has already will crash you before the target with 95% chance.
Also the code you sent is garbage and is taken from the Prometheus source.

<hr>

> TupoyeMenu doesn't support Lua scripts

That is just false, while existing *gui* YimMenu scripts won't work some basic functionality is supported.

<hr>

> If I add them myself it gives me a error that its not allowed

Add `override` after all member functions. Example:  `get_access_level` and `execute`.
```cpp
virtual CommandAccessLevel get_access_level() override
```
Also replace `const std::vector<std::uint64_t>& _args` with `const command_arguments& _args`.

**Comment by ClapperJuan** [comment]
> > [crash_player.zip](https://github.com/TupoyeMenu/TupoyeMenu/files/15408792/crash_player.zip) This seems to be working fine.
> 
> What building version did you use

Fast compile release I believe it was called and I basically did what tupoye suggested and added overrides

**Comment by Ahmad23145** [comment]
> I'm too lazy to add more crashes, even the two TupoyeMenu has already will crash you before the target with 95% chance. Also the code you sent is garbage and is taken from the Prometheus source.
> 
> > TupoyeMenu doesn't support Lua scripts
> 
> That is just false, while existing _gui_ YimMenu scripts won't work some basic functionality is supported.
> 
> > If I add them myself it gives me a error that its not allowed
> 
> Add `override` after all member functions. Example: `get_access_level` and `execute`.
> 
> ```c++
> virtual CommandAccessLevel get_access_level() override
> ```
> 
> Also replace `const std::vector<std::uint64_t>& _args` with `const command_arguments& _args`.

@tupoy-ya I added them but if i open the menu it says "INVALID COMMAND" anyhow to fix?

![Screenshot (7)](https://github.com/TupoyeMenu/TupoyeMenu/assets/165480150/701377a8-878f-4482-8bb3-ed535dd6f0a8)

**Comment by ClapperJuan** [comment]
Your command name is not matching the name given in the commands code is what I would assume is happening

**Comment by Ahmad23145** [comment]
> Your command name is not matching the name given in the commands code is what I would assume is happening

Could you show me the correct commands code?

**Comment by Ahmad23145** [comment]
I just figured it out

**Comment by Ahmad23145** [comment]
TSE Crash doesnt work
