### ISSUE TITLE
[Bug]: TSE CRASH TREATED AN ERROR WHEN COMPILING

### ISSUE THREAD

**Issue by Ahmad23145** [tupoy-ya/TupoyeMenu#91]
### Describe the bug

The build doesn't compile

### Steps To Reproduce

1. Go to Visual Studio C++ 2. Compile the Build 3. See error

### Expected Behavior

To not see error

### Logs

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	LNK1257	code generation failed	C:\Users\Administrator\Source\Repos\TupoyeMenu\out\build\x64-Release\YimMenu	C:\Users\Administrator\Source\Repos\TupoyeMenu\out\build\x64-Release\LINK	1		
 
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2220	the following warning is treated as an error	C:\Users\Administrator\Source\Repos\TupoyeMenu\out\build\x64-Release\TupoyeMenu	C:\Users\Administrator\Source\Repos\TupoyeMenu\src\backend\commands\player\crash\tse_crash.cpp	30		
```

### Store

Epic Games

### Language

English

### Additional context

I think it needs an Intializer

### Build

- [X] I've confirmed the issue exists on the latest version of TupoyeMenu and does not exist on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by Ahmad23145** [comment]
@tupoy-ya Will you fix this?

**Comment by tupoy-ya** [comment]
Please test on the latest commit and post the full log if it still doesn't work.

**Comment by tupoy-ya** [comment]
No response from author, no full logs, should be fixed.
