### ISSUE TITLE
[Build]: cmake error Illegal characters in path.

### ISSUE THREAD

**Issue by aynonomous-D** [tupoy-ya/TupoyeMenu#99]
### Describe the build issues

CMake Generation Failed.    

### Screenshots and/or Logs

1> CMake generation started for configuration: 'x64-Release'.
1> Command line: "C:\Windows\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "c:\program files\microsoft visual studio\2022\professional\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_INSTALL_PREFIX:PATH="D:\projects\TupoyeMenu\TupoyeMenu\out\install\x64-Release" -DOPTIMIZE:BOOL="YES" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe"   -DCMAKE_MAKE_PROGRAM="c:\program files\microsoft visual studio\2022\professional\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "D:\projects\TupoyeMenu\TupoyeMenu" 2>&1"
1> Working directory: D:\projects\TupoyeMenu\TupoyeMenu\out\build\x64-Release
1> [CMake] Git found: C:/Program Files/Git/cmd/git.exe
1> [CMake] 
1> [CMake] Fetching modules
1> [CMake] asmjit
1> [CMake] ** AsmJit Summary **
1> [CMake]    ASMJIT_DIR=D:/projects/TupoyeMenu/TupoyeMenu/out/build/x64-Release/_deps/asmjit-src
1> [CMake]    ASMJIT_TEST=FALSE
1> [CMake]    ASMJIT_TARGET_TYPE=STATIC
1> [CMake]    ASMJIT_DEPS=
1> [CMake]    ASMJIT_LIBS=asmjit
1> [CMake]    ASMJIT_CFLAGS=-DASMJIT_STATIC;-DASMJIT_NO_AARCH64;-DASMJIT_NO_FOREIGN
1> [CMake]    ASMJIT_PRIVATE_CFLAGS=-MP;-GF;-Zc:__cplusplus;-Zc:inline;-Zc:strictStrings;-Zc:threadSafeInit-;-W4;-DASMJIT_STATIC;-DASMJIT_NO_AARCH64;-DASMJIT_NO_FOREIGN
1> [CMake]    ASMJIT_PRIVATE_CFLAGS_DBG=-GS
1> [CMake]    ASMJIT_PRIVATE_CFLAGS_REL=-GS-;-O2;-Oi
1> [CMake] MinHook
1> [CMake] CMake Deprecation Warning at out/build/x64-Release/_deps/minhook-src/CMakeLists.txt:27 (cmake_minimum_required):
1> [CMake]   Compatibility with CMake < 3.5 will be removed from a future version of
1> [CMake]   CMake.
1> [CMake] 
1> [CMake]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
1> [CMake]   CMake that the project does not need compatibility with older versions.
1> [CMake] 
1> [CMake] 
1> [CMake] AsyncLogger
1> [CMake] -- Using std::format for formatting, you can set USE_FMT to force fmt::format instead.
1> [CMake] pugixml
1> [CMake] CMake Deprecation Warning at out/build/x64-Release/_deps/pugixml-src/CMakeLists.txt:1 (cmake_minimum_required):
1> [CMake]   Compatibility with CMake < 3.5 will be removed from a future version of
1> [CMake]   CMake.
1> [CMake] 
1> [CMake]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
1> [CMake]   CMake that the project does not need compatibility with older versions.
1> [CMake] 
1> [CMake] 
1> [CMake] json
1> [CMake] CMake Deprecation Warning at out/build/x64-Release/_deps/json-src/CMakeLists.txt:1 (cmake_minimum_required):
1> [CMake]   Compatibility with CMake < 3.5 will be removed from a future version of
1> [CMake]   CMake.
1> [CMake] 
1> [CMake]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
1> [CMake]   CMake that the project does not need compatibility with older versions.
1> [CMake] 
1> [CMake] 
1> [CMake] -- Using the single-header code from D:/projects/TupoyeMenu/TupoyeMenu/out/build/x64-Release/_deps/json-src/single_include/
1> [CMake] Lua
1> [CMake] CMake Deprecation Warning at out/build/x64-Release/_deps/lua-src/CMakeLists.txt:1 (cmake_minimum_required):
1> [CMake]   Compatibility with CMake < 3.5 will be removed from a future version of
1> [CMake]   CMake.
1> [CMake] 
1> [CMake]   Update the VERSION argument <min> value or use a ...<max> suffix to tell
1> [CMake]   CMake that the project does not need compatibility with older versions.
1> [CMake] 
1> [CMake] 
1> [CMake] 
1> [CMake] Fetching custom modules
1> [CMake] ImGui
1> [CMake] GTAV-Classes
1> [CMake] -- TupoyeMenu
1> [CMake] -- Configuring done (7.5s)
1> [CMake] -- Generating done (0.2s)
1> [CMake] -- Build files have been written to: D:/projects/TupoyeMenu/TupoyeMenu/out/build/x64-Release
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Error: Illegal characters in path.

### IDE/Compiler

Visual Studio 2022

### Setup Guide

- [X] I confirm that I followed the setup guide correctly.

### YimMenu Source Code

- [X] I've confirmed this is an issue with building unmodified YimMenu.

**Comment by tupoy-ya** [comment]
Does building YimMenu actually work?
I tested TupoyeMenu with Visual Studio CMake and it works fine for me.

Just a random thought: does your windows username contain non ascii characters?

Maybe try building from the CLI:
https://github.com/YimMenu/YimMenu/wiki/Setup-your-PC-for-YimMenu-Development#no-ide-or-cli
